name: ubuntu-matrix

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-build_and_test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ ! env.ACT }}
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: printenv
        run: |
          printenv
      - name: make
        run: |
          make submodules
          make all
      - name: make install
        run: |
          sudo -S make install
      - name: man nostril
        run: |
          type -P nostril && man nostril || echo "man nostril not working..."
      - name: nostril
        run: |
          #pipe handles non-zero return from nostril default help
          sudo make install > /dev/null 2>&1
          type -P nostril && nostril --envelope -t nostril --content ""
